name: 'Documentation Spell Check'
description: 'Checks spelling in documentation'
inputs:
  working-directory:
    description: 'Working directory'
    required: true
    default: '.'
  makefile:
    description: 'Name of the Makefile to use (default: "Makefile.sp" if it exists, "Makefile" otherwise)'
    required: false
    type: string
    default: 'use-default'
  install-target:
    description: 'Target to run to install the tools (default: "install")'
    required: false
    type: string
    default: 'install'
  spelling-target:
    description: 'Target to run for the spelling check (default: "spelling")'
    required: false
    type: string
    default: 'spelling'
runs:
  using: 'composite'
  steps:
    - run: python3 $GITHUB_ACTION_PATH/spellcheck.py ${{ inputs.working-directory }} --install_target ${{ inputs.install-target }} --spelling_target ${{ inputs.spelling-target }} --makefile ${{ inputs.makefile }}
      shell: bash
