name: 'Inclusive Language Check'
description: 'Checks for inclusive language in documentation'
inputs:
  working-directory:
    description: 'Working directory'
    required: true
    default: '.'
  makefile:
    description: 'Name of the Makefile to use (default: "Makefile.sp" if it exists, "Makefile" otherwise)'
    required: false
    type: string
    default: 'use-default'
  install-target:
    description: 'Target to run to install the tools (default: "install")'
    required: false
    type: string
    default: 'install'
  woke-target:
    description: 'Target to run for the inclusive language check (default: "woke")'
    required: false
    type: string
    default: 'woke'
runs:
  using: 'composite'
  steps:
    - run: python3 $GITHUB_ACTION_PATH/inclusive_language.py ${{ inputs.working-directory }} --woke_target ${{ inputs.woke-target }} --makefile ${{ inputs.makefile }}
      shell: bash