name: Automatic documentation checks

on:
  workflow_call:
    inputs:
      working-directory:
        description: 'Working directory'
        required: true
        type: string
      python-version:
        description: 'Version of the Python interpreter to use (defaults to 3.10)'
        required: false
        type: string
        default: '3.10'
      makefile:
        description: 'Name of the Makefile to use (default: "Makefile.sp" if it exists, "Makefile" otherwise)'
        required: false
        type: string
        default: 'use-default'
      install-target:
        description: 'Target to run to install the tools (default: "install")'
        required: false
        type: string
        default: 'install'
      spelling-target:
        description: 'Target to run for the spelling check (default: "spelling")'
        required: false
        type: string
        default: 'spelling'
      woke-target:
        description: 'Target to run for the inclusive language check (default: "woke")'
        required: false
        type: string
        default: 'woke'
      linkcheck-target:
        description: 'Target to run for the link check (default: "linkcheck")'
        required: false
        type: string
        default: 'linkcheck'
      fetch-depth:
        description: 'Fetch depth to support timestamps'
        required: false
        type: string
        default: '0'
      runs-on:
        description: 'GitHub runners'
        required: false
        type: string
        default: '["ubuntu-24.04"]'

    outputs:
      spellcheck-result:
        description: "Result of the spelling check"
        value: ${{ jobs.spellcheck.outputs.result }}
      woke-result:
        description: "Result of the inclusive language check"
        value: ${{ jobs.inclusive-language.outputs.result }}
      linkcheck-result:
        description: "Result of the link check"
        value: ${{ jobs.linkcheck.outputs.result }}

jobs:
  spellcheck:
    name: Spell check
    uses: ./.github/workflows/spelling-check.yaml
    with:
      working-directory: ${{ inputs.working-directory }}
      python-version: ${{ inputs.python-version }}
      install-target: ${{ inputs.install-target }}
      spelling-target: ${{ inputs.spelling-target }}
      makefile: ${{ inputs.makefile }}
      fetch-depth: ${{ inputs.fetch-depth }}
      runs-on: ${{ inputs.runs-on }}

  inclusive-language:
    name: Inclusive language check
    uses: ./.github/workflows/inclusive-language-check.yaml
    with:
      working-directory: ${{ inputs.working-directory }}
      python-version: ${{ inputs.python-version }}
      install-target: ${{ inputs.install-target }}
      woke-target: ${{ inputs.woke-target }}
      makefile: ${{ inputs.makefile }}
      fetch-depth: ${{ inputs.fetch-depth }}
      runs-on: ${{ inputs.runs-on }}

  linkcheck:
    name: Link check
    uses: ./.github/workflows/link-check.yaml
    with:
      working-directory: ${{ inputs.working-directory }}
      python-version: ${{ inputs.python-version }}
      install-target: ${{ inputs.install-target }}
      linkcheck-target: ${{ inputs.linkcheck-target }}
      makefile: ${{ inputs.makefile }}
      fetch-depth: ${{ inputs.fetch-depth }}
      runs-on: ${{ inputs.runs-on }}
