name: Documentation spelling check

on:
  workflow_call:
    inputs:
      working-directory:
        description: 'Working directory'
        required: true
        type: string
      python-version:
        description: 'Version of the Python interpreter to use (defaults to 3.10)'
        required: false
        type: string
        default: '3.10'
      makefile:
        description: 'Name of the Makefile to use (default: "Makefile.sp" if it exists, "Makefile" otherwise)'
        required: false
        type: string
        default: 'use-default'
      install-target:
        description: 'Target to run to install the tools (default: "install")'
        required: false
        type: string
        default: 'install'
      spelling-target:
        description: 'Target to run for the spelling check (default: "spelling")'
        required: false
        type: string
        default: 'spelling'
      fetch-depth:
        description: 'Fetch depth to support timestamps'
        required: false
        type: string
        default: '0'
      runs-on:
        description: 'GitHub runners'
        required: false
        type: string
        default: '["ubuntu-24.04"]'
    outputs:
      spellcheck-result:
        description: "Result of the spelling check"
        value: ${{ jobs.spellcheck.outputs.result }}

jobs:
  spellcheck:
    name: Check spelling in the documentation
    runs-on: ${{ fromJson(inputs.runs-on) }}
    outputs:
      result: ${{ steps.spellcheck-step.outcome }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: ${{ inputs.fetch-depth }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}

      - name: Spell Check
        id: spellcheck-step
        uses: canonical/documentation-workflows/spellcheck@main
        with:
          working-directory: ${{ inputs.working-directory }}
          install-target: ${{ inputs.install-target }}
          spelling-target: ${{ inputs.spelling-target }}
          makefile: ${{ inputs.makefile }}
